# Generated by Django 5.1.3 on 2024-11-19 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description_of_direction', models.TextField()),
                ('start_of_the_trip', models.DateField(default=django.utils.timezone.now)),
                ('end_of_the_trip', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
